过滤数据与拆关节

In [32]:
import pandas as pd
import numpy as np

In [3]:
!ls

alldata.csv     col.out         未命名.ipynb


In [4]:
data = pd.read_csv('alldata.csv',header=None,sep=';')

In [5]:
data.head()

0          1              2    3   4  5   6   7   8  9   ...    56  \
0  Zu3100002  719060101  1693929865875  0x0   0  f   0   1   0  f  ...  44.0   
1  Zu3100002  719060101  1693929864901  0x0   0  f   0   1   0  f  ...  44.0   
2  Zu3100002  719060101  1659819922033  0x0   0  f   0   1   0  f  ...  44.0   
3  Zu3100002  719060101  1659819918855  0x0   0  f   0   1   0  f  ...  44.0   
4  Zu3100002  719060101  1659819915642  0x0   0  f   0   1   0  f  ...  44.0   

     57    58    59    60    61    62    63  64  65  
0  45.0  48.0  48.0  48.0  48.0  48.0  48.0 NaN   1  
1  45.0  48.0  48.0  48.0  48.0  48.0  48.0 NaN   1  
2  45.0  48.0  48.0  48.0  48.0  48.0  48.0 NaN   1  
3  45.0  48.0  48.0  48.0  48.0  48.0  48.0 NaN   1  
4  45.0  48.0  48.0  48.0  48.0  48.0  48.0 NaN   1  

[5 rows x 66 columns]

In [6]:
col_list = ['robot_id','cabinet_id','rtc','error_code','protective_stop','paused','emergency_stop','task_state',
'interp_state','enabled','powered_on','drag_status','rapid_rate','inpos','cur_running_time','sum_running_time',
'joint_1_actual_position','joint_2_actual_position','joint_3_actual_position','joint_4_actual_position','joint_5_actual_position','joint_6_actual_position',
'ins_average_power_1','ins_average_power_2','ins_average_power_3','ins_average_power_4','ins_average_power_5','ins_average_power_6',
'cur_running_circles_1','cur_running_circles_2','cur_running_circles_3','cur_running_circles_4','cur_running_circles_5','cur_running_circles_6',
'sum_running_circles_1','sum_running_circles_2','sum_running_circles_3','sum_running_circles_4','sum_running_circles_5','sum_running_circles_6',
'actual_position_1','actual_position_2','actual_position_3','actual_position_4','actual_position_5','actual_position_6',
'current_fluctuation_1','current_fluctuation_2','current_fluctuation_3','current_fluctuation_4','current_fluctuation_5','current_fluctuation_6',
'inst_temperature_1','inst_temperature_2','inst_temperature_3','inst_temperature_4','inst_temperature_5','inst_temperature_6',
'inst_voltage_1','inst_voltage_2','inst_voltage_3','inst_voltage_4','inst_voltage_5','inst_voltage_6',
'receive_time','task_mode']

In [8]:
data.columns = col_list

In [9]:
data

robot_id  cabinet_id            rtc error_code  protective_stop  \
0         Zu3100002   719060101  1693929865875        0x0                0   
1         Zu3100002   719060101  1693929864901        0x0                0   
2         Zu3100002   719060101  1659819922033        0x0                0   
3         Zu3100002   719060101  1659819918855        0x0                0   
4         Zu3100002   719060101  1659819915642        0x0                0   
...             ...         ...            ...        ...              ...   
4712814  Zu12100012  2019101010  1625447978121        0x0                0   
4712815   Zu7260013  2019101010  1625447978064        0x0                0   
4712816    Zu710001   719060101  1625447977633        0x0                0   
4712817   Zu7200001   719060101  1625447977442        0x0                0   
4712818    Zu710001  2019101010  1625447889010        0x0                0   

        paused  emergency_stop  task_state  interp_state enabled  ...  \
0            f               0           1             0       f  ...   
1            f               0           1             0       f  ...   
2            f               0           1             0       f  ...   
3            f               0           1             0       f  ...   
4            f               0           1             0       f  ...   
...        ...             ...         ...           ...     ...  ...   
4712814      f               1           1             0       f  ...   
4712815      f               0           4             0       t  ...   
4712816      f               0           4             0       t  ...   
4712817      f               0           1             0       f  ...   
4712818      f               1           1             0       f  ...   

         inst_temperature_5 inst_temperature_6  inst_voltage_1 inst_voltage_2  \
0                      44.0               45.0            48.0           48.0   
1                      44.0               45.0            48.0           48.0   
2                      44.0               45.0            48.0           48.0   
3                      44.0               45.0            48.0           48.0   
4                      44.0               45.0            48.0           48.0   
...                     ...                ...             ...            ...   
4712814                 0.0                0.0             0.0            0.0   
4712815                 0.0                0.0             0.0            0.0   
4712816                 0.0                0.0             0.0            0.0   
4712817                 0.0                0.0             0.0            0.0   
4712818                 0.0                0.0             0.0            0.0   

         inst_voltage_3  inst_voltage_4  inst_voltage_5  inst_voltage_6  \
0                  48.0            48.0            48.0            48.0   
1                  48.0            48.0            48.0            48.0   
2                  48.0            48.0            48.0            48.0   
3                  48.0            48.0            48.0            48.0   
4                  48.0            48.0            48.0            48.0   
...                 ...             ...             ...             ...   
4712814             0.0             0.0             0.0             0.0   
4712815             0.0             0.0             0.0             0.0   
4712816             0.0             0.0             0.0             0.0   
4712817             0.0             0.0             0.0             0.0   
4712818             0.0             0.0             0.0             0.0   

         receive_time  task_mode  
0                 NaN          1  
1                 NaN          1  
2                 NaN          1  
3                 NaN          1  
4                 NaN          1  
...               ...        ...  
4712814           NaN          1  
4712815           NaN          1  
4712816 

In [15]:
# data.columns

In [21]:
data['robot_id'].unique()

array(['Zu3100002', 'Zu3100161', 'Zu3110001', 'Zu710001', 'Zu7260001',
       'Zu7210013', 'Zu7250098', 'Zu12110056', 'Zu7210015', 'Zu0',
       'Zu7250057', 'Zu7210070', 'Zu7250763', 'Zu12100052', 'Zu7250396',
       'Zu7250085', 'Zu7210038', 'Zu7250397', 'Zu18100047', 'Zu12100168',
       'Zu7250383', 'C7300105', 'Zu7250422', 'Zu7250197', 'Zu3110009',
       'Zu12100012', 'MC11150101', 'Zu7260013', 'Zu3100091', 'Zu7200001'],
      dtype=object)

In [11]:
data['inpos'].unique()

array(['t', 'f'], dtype=object)

In [13]:
data.shape

(4712819, 66)

筛选 在运动，上使能，真机

In [22]:
data_clean = data[(data['inpos']=='f') & (data['task_state']==4) & (data['inst_temperature_1'] >0)]
data_clean.shape

(589593, 66)

In [34]:
data_clean['emergency_stop'].unique()

array([0])

In [24]:
data_clean['task_state'].unique()

array([4])

In [27]:
data_clean['protective_stop'].unique()

array([0, 1])

In [29]:
data_clean['paused'].unique()

array(['f', 't'], dtype=object)

In [39]:
np.sort(data_clean['inst_temperature_1'].unique())

array([26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60.])

In [26]:
data_clean.head()

robot_id  cabinet_id            rtc error_code  protective_stop  \
23212  Zu7250098           0  1628643756145        0x0                0   
23216  Zu3100161  2019101010  1628643755723        0x0                0   
23222  Zu3100161  2019101010  1628643752846        0x0                0   
23224  Zu7250098           0  1628643752716        0x0                0   
23231  Zu3100161  2019101010  1628643749708        0x0                0   

      paused  emergency_stop  task_state  interp_state enabled  ...  \
23212      f               0           4             1       t  ...   
23216      f               0           4             1       t  ...   
23222      f               0           4             1       t  ...   
23224      f               0           4             1       t  ...   
23231      f               0           4             1       t  ...   

       inst_temperature_5 inst_temperature_6  inst_voltage_1 inst_voltage_2  \
23212                53.0               53.0            47.0           47.0   
23216                47.0               48.0            48.0           48.0   
23222                47.0               48.0            48.0           48.0   
23224                53.0               53.0            48.0           48.0   
23231                47.0               48.0            48.0           48.0   

       inst_voltage_3  inst_voltage_4  inst_voltage_5  inst_voltage_6  \
23212            47.0            47.0            47.0            47.0   
23216            48.0            48.0            48.0            47.0   
23222            47.0            48.0            47.0            47.0   
23224            48.0            47.0            47.0            47.0   
23231            48.0            48.0            48.0            47.0   

       receive_time  task_mode  
23212           NaN          2  
23216           NaN          2  
23222           NaN          2  
23224           NaN          2  
23231           NaN          2  

[5 rows x 66 columns]

In [25]:
data_clean.columns

Index(['robot_id', 'cabinet_id', 'rtc', 'error_code', 'protective_stop',
       'paused', 'emergency_stop', 'task_state', 'interp_state', 'enabled',
       'powered_on', 'drag_status', 'rapid_rate', 'inpos', 'cur_running_time',
       'sum_running_time', 'joint_1_actual_position',
       'joint_2_actual_position', 'joint_3_actual_position',
       'joint_4_actual_position', 'joint_5_actual_position',
       'joint_6_actual_position', 'ins_average_power_1', 'ins_average_power_2',
       'ins_average_power_3', 'ins_average_power_4', 'ins_average_power_5',
       'ins_average_power_6', 'cur_running_circles_1', 'cur_running_circles_2',
       'cur_running_circles_3', 'cur_running_circles_4',
       'cur_running_circles_5', 'cur_running_circles_6',
       'sum_running_circles_1', 'sum_running_circles_2',
       'sum_running_circles_3', 'sum_running_circles_4',
       'sum_running_circles_5', 'sum_running_circles_6', 'actual_position_1',
       'actual_position_2', 'actual_position_3', 'actu

In [41]:
data_clean = data_clean[['robot_id','rtc','protective_stop','task_state','rapid_rate','sum_running_time',
'ins_average_power_1', 'ins_average_power_2','ins_average_power_3', 'ins_average_power_4', 'ins_average_power_5','ins_average_power_6', 
'sum_running_circles_1', 'sum_running_circles_2','sum_running_circles_3', 'sum_running_circles_4','sum_running_circles_5', 'sum_running_circles_6', 'joint_1_actual_position',
       'joint_2_actual_position', 'joint_3_actual_position',
       'joint_4_actual_position', 'joint_5_actual_position',
       'joint_6_actual_position', 'current_fluctuation_1',
       'current_fluctuation_2', 'current_fluctuation_3',
       'current_fluctuation_4', 'current_fluctuation_5',
       'current_fluctuation_6', 'inst_temperature_1', 'inst_temperature_2',
       'inst_temperature_3', 'inst_temperature_4', 'inst_temperature_5',
       'inst_temperature_6', 'inst_voltage_1', 'inst_voltage_2',
       'inst_voltage_3', 'inst_voltage_4', 'inst_voltage_5', 'inst_voltage_6',]]

In [ ]:
df1 = data_clean[['robot_id', 'rtc', 'protective_stop', 'task_state', 'interp_state','sum_running_time',
                  'ins_average_power_1','sum_running_circles_1','joint_1_actual_position',
           ]
                 

拆关节

In [62]:
col_list=['robot_id','rtc','protective_stop','task_state','rapid_rate','sum_running_time',
          'ins_average_power_1','sum_running_circles_1','joint_1_actual_position',
          'current_fluctuation_1','inst_temperature_1','inst_voltage_1']
data_ans = pd.DataFrame(columns=col_list)
for i in range(1,7):
    col_list_temp = [col.replace('1',str(i)) for col in col_list]
    
    data_temp = data_clean[col_list_temp]
    data_temp['joint'] = i
    data_temp.columns = col_list+['joint']
    data_ans = pd.concat([data_ans,data_temp])

/Users/jason/mambaforge/envs/jaka/lib/python3.8/site-packages/pandas/core/frame.py:3607: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_item(key, value)


In [76]:
data_ans.iloc[2::589593,:]

robot_id            rtc protective_stop task_state  rapid_rate  \
23222  Zu3100161  1628643752846               0          4         1.0   
23222  Zu3100161  1628643752846               0          4         1.0   
23222  Zu3100161  1628643752846               0          4         1.0   
23222  Zu3100161  1628643752846               0          4         1.0   
23222  Zu3100161  1628643752846               0          4         1.0   
23222  Zu3100161  1628643752846               0          4         1.0   

      sum_running_time  ins_average_power_1  sum_running_circles_1  \
23222         12364106                  3.8           1.070655e+06   
23222         12364106                  0.0           1.058824e+05   
23222         12364106                  0.0           2.160996e+05   
23222         12364106                  0.0           1.868055e+05   
23222         12364106                  0.0           1.229418e+05   
23222         12364106                  0.0           1.557844e+05   

       joint_1_actual_position  current_fluctuation_1  inst_temperature_1  \
23222               249.018715                    1.1                46.0   
23222                87.266460                    0.3                49.0   
23222                -1.067734                    0.5                47.0   
23222                94.414440                    1.3                46.0   
23222                -2.798767                    0.8                47.0   
23222                -0.081711                    1.3                48.0   

       inst_voltage_1  joint  
23222            48.0      1  
23222            48.0      2  
23222            47.0      3  
23222            48.0      4  
23222            47.0      5  
23222            47.0      6

In [68]:
data_ans

robot_id            rtc protective_stop task_state  rapid_rate  \
23212    Zu7250098  1628643756145               0          4         1.0   
23216    Zu3100161  1628643755723               0          4         1.0   
23222    Zu3100161  1628643752846               0          4         1.0   
23224    Zu7250098  1628643752716               0          4         1.0   
23231    Zu3100161  1628643749708               0          4         1.0   
...            ...            ...             ...        ...         ...   
4712686  Zu3100091  1625448181050               0          4         1.0   
4712696  Zu3100091  1625448179554               0          4         1.0   
4712704  Zu3100091  1625448178687               0          4         1.0   
4712713  Zu3100091  1625448177444               0          4         1.0   
4712811  Zu3100091  1625447979405               0          4         1.0   

        sum_running_time  ins_average_power_1  sum_running_circles_1  \
23212           12589525            15.000000           3.016309e+05   
23216           12364110             3.400000           1.070656e+06   
23222           12364106             3.800000           1.070655e+06   
23224           12589521            36.400002           3.016302e+05   
23231           12364104            12.400000           1.070654e+06   
...                  ...                  ...                    ...   
4712686         12330690             0.300000           1.888191e+05   
4712696         12330688             0.500000           1.888189e+05   
4712704         12330688             0.100000           1.888189e+05   
4712713         12330686             0.100000           1.888188e+05   
4712811         12330488             0.400000           1.888064e+05   

         joint_1_actual_position  current_fluctuation_1  inst_temperature_1  \
23212                  51.366797                    1.0                54.0   
23216                 179.126535                    1.5                46.0   
23222                 249.018715                    1.1                46.0   
23224                  56.552356                    0.8                54.0   
23231                 134.857509                    2.2                46.0   
...                          ...                    ...                 ...   
4712686                32.793401                    0.8                50.0   
4712696                54.094375                    0.8                50.0   
4712704                63.405684                    0.3                50.0   
4712713                20.751428                    0.3                50.0   
4712811                 2.966841                    0.8                50.0   

         inst_voltage_1  joint  
23212              47.0    1.0  
23216              48.0    1.0  
23222              48.0    1.0  
23224              48.0    1.0  
23231              48.0    1.0  
...                 ...    ...  
4712686            47.0    6.0  
4712696            47.0    6.0  
4712704            47.0    6.0  
4712713            47.0    6.0  
4712811            47.0    6.0  

[3537558 rows x 13 columns]

In [74]:
data_ans['joint'] = data_ans['joint'].apply(np.int8)

In [77]:
data_ans

robot_id            rtc protective_stop task_state  rapid_rate  \
23212    Zu7250098  1628643756145               0          4         1.0   
23216    Zu3100161  1628643755723               0          4         1.0   
23222    Zu3100161  1628643752846               0          4         1.0   
23224    Zu7250098  1628643752716               0          4         1.0   
23231    Zu3100161  1628643749708               0          4         1.0   
...            ...            ...             ...        ...         ...   
4712686  Zu3100091  1625448181050               0          4         1.0   
4712696  Zu3100091  1625448179554               0          4         1.0   
4712704  Zu3100091  1625448178687               0          4         1.0   
4712713  Zu3100091  1625448177444               0          4         1.0   
4712811  Zu3100091  1625447979405               0          4         1.0   

        sum_running_time  ins_average_power_1  sum_running_circles_1  \
23212           12589525            15.000000           3.016309e+05   
23216           12364110             3.400000           1.070656e+06   
23222           12364106             3.800000           1.070655e+06   
23224           12589521            36.400002           3.016302e+05   
23231           12364104            12.400000           1.070654e+06   
...                  ...                  ...                    ...   
4712686         12330690             0.300000           1.888191e+05   
4712696         12330688             0.500000           1.888189e+05   
4712704         12330688             0.100000           1.888189e+05   
4712713         12330686             0.100000           1.888188e+05   
4712811         12330488             0.400000           1.888064e+05   

         joint_1_actual_position  current_fluctuation_1  inst_temperature_1  \
23212                  51.366797                    1.0                54.0   
23216                 179.126535                    1.5                46.0   
23222                 249.018715                    1.1                46.0   
23224                  56.552356                    0.8                54.0   
23231                 134.857509                    2.2                46.0   
...                          ...                    ...                 ...   
4712686                32.793401                    0.8                50.0   
4712696                54.094375                    0.8                50.0   
4712704                63.405684                    0.3                50.0   
4712713                20.751428                    0.3                50.0   
4712811                 2.966841                    0.8                50.0   

         inst_voltage_1  joint  
23212              47.0      1  
23216              48.0      1  
23222              48.0      1  
23224              48.0      1  
23231              48.0      1  
...                 ...    ...  
4712686            47.0      6  
4712696            47.0      6  
4712704            47.0      6  
4712713            47.0      6  
4712811            47.0      6  

[3537558 rows x 13 columns]

In [78]:
data_clean.shape

(589593, 42)

In [79]:
589593*6

3537558

In [80]:
data_ans.columns=['robot_id','rtc','protective_stop','task_state','rapid_rate','sum_running_time',
          'ins_average_power','sum_running_circles','joint_actual_position','current_fluctuation','inst_temperature','inst_voltage','joint']

In [81]:
data_ans['joint'].unique()

array([1, 2, 3, 4, 5, 6], dtype=int8)

In [ ]:
data_ans.to_csv('data_clean_0811.csv')